language: node_js
node_js:
  - 12.10
before_install:
  - cd material-dashboard-react
script:
  - unset CI
  - npm install
  - npm run build
  - npm test [--a]
  after_success:
  - npm install -g firebase-tools
  - firebase deploy --token 1//0foBzNXPg3jzwCgYIARAAGA8SNwF-L9IrWoUnAMu7g5s3heW4b6n1oSmryo3ybQzu6S9qlWvoI0_Ue8izSI3igyyvKqGWUIV-8hw --non-interactive