language: node_js
node_js:
  - 12.10
before_install:
  - cd material-dashboard-react
script:
  - unset CI
  - npm install
  - npm run build
  - npm test [--a]
  after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive